/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


void generate_interrupt(void);
void change_accessLevel_to_NPAL(void);


/* This function executes in THREAD MODE + PAL of the processor */
int main(void)
{
    //printf("In THREAD MODE : Before interrupt\n");

    void (*func_ptr)(void); //creating a fn pointer
//    func_ptr = change_accessLevel_to_NPAL; //initialize 'func_ptr' with the address of the fn
    func_ptr = (void*) 0x80001fc;
    func_ptr(); //dereference the fn ptr and jump to that fn
    // the address of the fn is loaded into the PC. PC jumps to that fn

    //printf("In THREAD MODE : After interrupt\n");
	/* Loop forever */
	for(;;);
}


void change_accessLevel_to_NPAL(void) {
	// change 0th bit of CONTROL reg. -- 0-PAL, 1-NPAL
	__asm volatile("MRS R0, CONTROL");   // read
	__asm volatile("ORR R0, R0, #0x01"); // modify
	__asm volatile("MSR CONTROL, R0");   // write -- changing from PAL to NPAL
}


/* This function executes in THREAD MODE of the processor */
void generate_interrupt(void) {
	uint32_t *pSTIR  = (uint32_t* ) 0xE000EF00; // These addresses can only be accessed
	uint32_t *pISER0 = (uint32_t* ) 0xE000E100; // in PAL

	//Enable IRQ3 interrupt
	*pISER0 |= (1 << 3);
	//Generate an interrupt from s/w for IRQ3
	*pSTIR = (3 & 0x1FF);
	//check reg IPSR -> [8:0] ISR_NUMBER
}


/* This function(ISR) executes in HANDLER MODE of the processor */
void RTC_WKUP_IRQHandler(void) {
	printf("In HANDLER MODE : ISR\n");
}


void HardFault_Handler(void) {
	printf("Hard-fault detected\n"); // usage fault
	while(1);
}









