/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>


int main(void)
{
//	//------------------------ input operand ------------------------
//	uint32_t val = 5;
//	__asm volatile("MOV R0, %0": :"r"(val) ); // C-M4 devices generic_ug
//	// __asm volatile("MOV R0, %0": :"I"(val) ); //error
//	__asm volatile("MOV R0, %0": :"I"(0xAE) );
//	__asm volatile("MOV R0, %0": :"r"(0xFF) );

//	//------------------------ output operand ------------------------
////	uint32_t cntrl_reg;
////	__asm volatile("MRS %0, CONTROL" : "=r"(cntrl_reg) );
//	uint32_t xpsr_reg;
//	__asm volatile("MRS %0, PSR" : "=r"(xpsr_reg) );

//	//------------------------ output and input operands ------------------------
//	uint32_t var1=10, var2;
//	__asm volatile("MOV %0,%1" : "=r"(var2) : "r"(var1) );

	//------------------------ copy contents of ptr into another var------------------------
	uint32_t var1, *ptr;
	ptr = (uint32_t *) 0x20000008;
	__asm volatile("LDR %0, [%1]" : "=r"(var1) : "r"(ptr) );


	/* Loop forever */
	for(;;);
}
