/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{

	char msg1[] = "Hello, how are you?";

	printf("Message is: %s\n", msg1);
	printf("Address of msg1 is: %p\n", &msg1);
	printf("Value of msg1 is:   %#x\n", msg1);

	for(;;);

}
