/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>
#include "main.h"



#define DELAY 300000

int main(void)
{


	RCC_AHB1ENR_t* pRCCAHB1ENR    = (RCC_AHB1ENR_t* ) 0x40023830;
	GPIOx_MODER_t* pGpioAMode     = (GPIOx_MODER_t* ) 0x40020000 + 0x0;	//GPIO_A + GPIOx_MODER offset
	GPIOx_PUPDR_t* pGpioAPupd     = (GPIOx_PUPDR_t* ) 0x40020000 + 0x0C; //GPIO_A + GPIOx_PUPDR offset
	GPIOx_IDR_t const volatile *const pGpioAInData   = (GPIOx_IDR_t* )   0x40020000 + 0x10; //GPIO_A + GPIOx_IDR offset
	GPIOx_MODER_t* pGpioBMode     = (GPIOx_MODER_t* ) 0x40020400 + 0x0; //GPIO_B + GPIOx_MODER offset
	GPIOx_ODR_t*   pGpioBOutData  = (GPIOx_ODR_t* )   0x40020400 + 0x14; //GPIO_B + GPIOx_ODR offset
	
	//Clock enable
	pRCCAHB1ENR -> gpioA_en = 1;
	pRCCAHB1ENR -> gpioB_en = 1;
	
	//C1-4 i/p = PA1,2,3,8		R1-4 o/p = PB0,1,3,4
	//Configuring C1-4 as i/p and R1-4 as o/p
	pGpioAMode -> pin_1 = 0x0;	//C1	//cloumns -- i/p
	pGpioAMode -> pin_2 = 0x0;  //C2
	pGpioAMode -> pin_3 = 0x0;  //C3
	pGpioAMode -> pin_8 = 0x0;  //C4
	
	pGpioBMode -> pin_0 = 0x1;	//R1	//rows -- o/p
	pGpioBMode -> pin_1 = 0x1; //R2
	pGpioBMode -> pin_3 = 0x1; //R3
	pGpioBMode -> pin_4 = 0x1;	//R4
	
	//Pull-up registers enable for C1-4 
	pGpioAPupd -> pin_1 = 0x1;	//C1
	pGpioAPupd -> pin_2 = 0x1;  //C2
	pGpioAPupd -> pin_3 = 0x1;  //C3
	pGpioAPupd -> pin_8 = 0x1;  //C4
	
	//Configure all rows as HIGH
	pGpioBOutData -> pin_0 = 0x1;	//R1
	pGpioBOutData -> pin_1 = 0x1;	//R2
	pGpioBOutData -> pin_3 = 0x1;	//R3
	pGpioBOutData -> pin_4 = 0x1;	//R4
	
	
	while(1) {
		
		//R1 = LOW; rest = HIGH
		pGpioBOutData -> pin_0 = 0x0;	//R1
		pGpioBOutData -> pin_1 = 0x1;	//R2
		pGpioBOutData -> pin_3 = 0x1;	//R3
		pGpioBOutData -> pin_4 = 0x1;	//R4
		// if(!C1)
		if( !(pGpioAInData -> pin_0) )	{
			for(uint8_t i=0; i<DELAY; i++);	//switch-debouncing
			printf("Key pressed is: %c%d\n", 'S', 1);
		}
		/*else if( !(pGpioAInData -> pin_1) )	{
			for(uint8_t i=0; i<12000; i++);	//switch-debouncing
			printf("Key pressed is: %c%d\n", 'S', 2);
		}
		else if( !(pGpioAInData -> pin_2) )	{
			for(uint8_t i=0; i<12000; i++);	//switch-debouncing
			printf("Key pressed is: %c%d\n", 'S', 3);
		}
		else if( !(pGpioAInData -> pin_3) )	{
			for(uint8_t i=0; i<12000; i++);	//switch-debouncing
			printf("Key pressed is: %c%d\n", 'S', 4);
		}*/
		

		//R2 = LOW; rest = HIGH
		pGpioBOutData -> pin_0 = 0x1;	//R1
		pGpioBOutData -> pin_1 = 0x0;	//R2
		pGpioBOutData -> pin_3 = 0x1;	//R3
		pGpioBOutData -> pin_4 = 0x1;	//R4
		// if(!C1)
		if( !(pGpioAInData -> pin_0) )	{
			for(uint8_t i=0; i<DELAY; i++);	//switch-debouncing
			printf("Key pressed is: %c%d\n", 'S', 5);
		}
		/*else if( !(pGpioAInData -> pin_1) )	{
			for(uint8_t i=0; i<12000; i++);	//switch-debouncing
			printf("Key pressed is: %c%d\n", 'S', 6);
		}
		else if( !(pGpioAInData -> pin_2) )	{
			for(uint8_t i=0; i<12000; i++);	//switch-debouncing
			printf("Key pressed is: %c%d\n", 'S', 7);
		}
		else if( !(pGpioAInData -> pin_3) )	{
			for(uint8_t i=0; i<12000; i++);	//switch-debouncing
			printf("Key pressed is: %c%d\n", 'S', 8);
		}*/

	}
	
}
