/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
	uint32_t svcNumber = 0;
    __asm volatile("SVC #0x3"); //some SVC number for example

    __asm volatile("MOV %0, R0" : "=r"(svcNumber) : : );
    printf("In main()... svcNumber = 0x%lx\n", svcNumber);
	while(1);
}


__attribute__((naked)) void SVC_Handler(void) { //asm handler
	__asm volatile("TST LR, #0x4"); //Test bit[2] of EXC_RETURN
	__asm volatile("ITE EQ"); //if MSP -> bit[2]=0 -> 0&1=0 -> Z=1 -> EQ
	__asm volatile("MRSEQ R0, MSP");
	__asm volatile("MRSNE R0, PSP");
	__asm volatile("MOV R1, LR"); //EXC_RETURN
	__asm volatile("B SVC_Handler_C");
}


void SVC_Handler_C(uint32_t *pBaseStackFrame, uint32_t excReturn) { //C handler
	printf("In SVC_Handler...\n");

	uint8_t* next_instr_addr_after_svc = (uint8_t *) pBaseStackFrame[6]; //PC(return addr) = pBaseStackFrame + 6 words
	uint8_t svcNumber = *(next_instr_addr_after_svc - 2); //LSByte
	printf("SVC number = 0x%x\n", svcNumber);
	printf("EXC_RETURN value = 0x%lx\n", excReturn);

	//Increment SVCnumber by 4 and print it in Thread mode
	svcNumber+=4;
	pBaseStackFrame[0] = svcNumber; //Use the stackFrame itself to pass data from SVC_Handler to Thread mode
}




