/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

// Load 2 values from the memory
// Add them
// Store the result back into the memory

int main(void)
{
	__asm volatile("LDR R1,=#0x20001000"); //dst, src 	//load immediate value
	__asm volatile("LDR R2,=#0x20001004");
	__asm volatile("LDR R0, [R1]"); //dst, src
	__asm volatile("LDR R1, [R2]");
	__asm volatile("ADD R0, R0, R1"); //dst, src1, src2
	__asm volatile("STR R0, [R2]"); //src, dst


	/* Loop forever */
	for(;;);
}
