/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#define ALIAS_BASE 0x22000000
#define BITBAND_BASE 0x20000000

//Modify bit-[7] of mem. loc. 0x2000_0200 using its alias address

int main(void)
{
	uint8_t *ptrGivenReg = (uint8_t *) 0x20000200; //given address to be modified
	*ptrGivenReg = 0xFF; //first initialize to 0xFF

	//Normal method -- read, modify(bit-masking op.), write
	*ptrGivenReg &= ~( 1 << 7 ); //clear 7th bit

	*ptrGivenReg = 0xFF; //again initialize back to 0xFF

	//bit-band method
	//uint8_t *aliasAddr = ALIAS_BASE + ( 32 * (BITBAND_MEM_ADDR - BITBAND_BASE) ) + BIT*4; //formula to calculate the Alias address
	uint8_t *aliasAddr = (uint8_t *) ALIAS_BASE + ( 32 * (0x20000200 - BITBAND_BASE) ) + 7*4; //calculating alias address
	*aliasAddr = 0; //clearing bit-[7] of address 0x20000200


	/* Loop forever */
	for(;;);
}
