/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include<stdio.h>

int main(void)
{

	printf("Size of char is: %u\n\r", sizeof(char) );
	printf("Size of short is: %u\n\r", sizeof(short) );
	printf("Size of int is: %u\n\r", sizeof(int) );
	printf("Size of long is: %u\n\r", sizeof(long) );
	printf("Size of long long is: %u\n\r", sizeof(long long) );
	printf("Size of float is: %u\n\r", sizeof(float) );
	printf("Size of double is: %u\n\r", sizeof(double) );

	/* Loop forever */
	for(;;);
}
