/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

void hello(void);

int main(void)
{

    hello();

    printf("hello fn addr = %p\n", hello);
    printf("hello fn addr = %p\n", &hello);

    /* Loop forever */
	for(;;);
}


void hello(void) {
    printf("Hello\n");
}




