/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

int main(void)
{
	RCC_AHB1ENR_t* pRCCAHB1ENR    = (RCC_AHB1ENR_t* ) 0x40023830;
	GPIOx_MODER_t* pGpioGMode     = (GPIOx_MODER_t* ) 0x40021800;
	GPIOx_ODR_t*   pGpioGOutData  = (GPIOx_ODR_t* )   0x40021814;

    //1. Enable clk for GPIO-D peripheral in RCC_AHB1ENR
	pRCCAHB1ENR -> gpiog_en = 1;

    //2. Configure the mode of the IO pin as OP
    //a. Clear [27:26] bits ??
    pGpioGMode -> moder_13 = 1;
    //b. Set 26 bit
    //*pPortDModeReg |= (1<<26);

    //3. Toggle 13 bit of ODR to make PG13-LED (Green)
    //*pPortDOutReg |= (1<<13);
    while(1)	{
    	for(uint32_t i=300000; i>0 ; i--);
    	pGpioGOutData -> odr_13 ^= 1;
    }


}

