/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>

int main(void)
{
    printf("Hello world!\n");
    printf("Who let the dogs out???\n");
    printf("Stairway to heaven...\n");

    char c1 = -1;
    //signed char c2 = -1;

    if(c1 > 0) {
    	printf("c1 is positive\n");
    }
    else {
    	printf("c1 is negative\n");
    }


/////////////// 002a_sizeof /////////////////////

    printf("Size of char is: %u\n", sizeof(char) );
    printf("Size of short is: %u\n", sizeof(short) );
    printf("Size of int is: %u\n", sizeof(int) );
    printf("Size of long is: %u\n", sizeof(long) );
    printf("Size of long long is: %u\n", sizeof(long long) );
    printf("Size of float is: %u\n", sizeof(float) );
    printf("Size of double is: %u\n", sizeof(double) );

/////////////////////////////////////////////////

	/* Loop forever */
	for(;;);
}
