/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define USART2_IRQNO 38
#define USART3_IRQNO 39

int main(void)
{
	uint32_t *pISER1 = (uint32_t *) 0xE000E104;
	uint32_t *pISPR1 = (uint32_t *) 0xE000E204;

	*pISPR1 = (1 << (USART3_IRQNO % 32) );
	*pISPR1 = (1 << (USART2_IRQNO % 32) );

	*pISER1 = (1 << (USART3_IRQNO % 32) );

    /* Loop forever */
	for(;;);
}


void USART3_IRQHandler(void) {
	printf("Inside USART3 interrupt handler\n");
}
