/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#define USART3_IRQNO 39

int main(void)
{
    //1. Manually pend the pending bit for USART3 IRQ number in NVIC
	uint32_t *pISPR1 = (uint32_t *) 0xE000E204; //NVIC_ISPR_1
	*pISPR1 |= ( 1 << (USART3_IRQNO % 32) );


	//2. Enable USART3 IRQ number in NVIC
	uint32_t *pISER1 = (uint32_t *) 0xE000E104; //NVIC_ISER_1
	*pISER1 |= ( 1 << (USART3_IRQNO % 32) );

	/* Loop forever */
	for(;;);
}


//USART3 ISR
void USART3_IRQHandler(void) { //from startup file <>.s
	printf("In USART3 ISR\n");
}
