/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>

int main(void)
{
    printf("Hello world!\n");
    printf("Who let the dogs out???\n");
    printf("Stairway to heaven...\n");

    signed char c1 = -1;

    if(c1 > 0) {
    	printf("c1 is positive\n");
    }
    else {
    	printf("c1 is negative\n");
    }

	/* Loop forever */
	for(;;);
}
