/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>

int g_num1 = -2000;
int g_num2 = 400;
//int result;

int main(void)
{

	int result;

	result = g_num1 + g_num2;
	printf("Result = %d\n", result);

	/* Loop forever */
	for(;;);
}
