/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


void generate_interrupt(void);



/* This function executes in THREAD MODE of the processor */
int main(void)
{
    printf("In THREAD MODE : Before interrupt\n");
    generate_interrupt(); //bl instruction - branch & link
    //LR gets updated with the return address
    printf("In THREAD MODE : After interrupt\n");
	/* Loop forever */
	for(;;);
}


/* This function executes in THREAD MODE of the processor */
void generate_interrupt(void) {
	uint32_t *pSTIR  = (uint32_t* ) 0xE000EF00;
	uint32_t *pISER0 = (uint32_t* ) 0xE000E100;

	//Enable IRQ3 interrupt
	*pISER0 |= (1 << 3);
	//Generate an interrupt from s/w for IRQ3
	*pSTIR = (3 & 0x1FF);
	//check reg IPSR -> [8:0] ISR_NUMBER
}


/* This function(ISR) executes in HANDLER MODE of the processor */
void RTC_WKUP_IRQHandler(void) {
	printf("In HANDLER MODE : ISR\n");
}












