/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


int main(void)
{
    uint32_t* pClkCtrlReg   = (uint32_t* ) 0x40023830;
    uint32_t* pPortDModeReg = (uint32_t* ) 0x40021800;
    uint32_t* pPortDOutReg  = (uint32_t* ) 0x40021814;

    //1. Enable clk for GPIO-D peripheral in RCC_AHB1ENR
    *pClkCtrlReg |= (1<<6);

    //2. Configure the mode of the IO pin as OP
    //a. Clear [27:26] bits ??
    *pPortDModeReg &= ~(1<<27);
    //b. Set 26 bit
    *pPortDModeReg |= (1<<26);

    //3. Set 13 bit of ODR to make PG13-LED (Green) HIGH
    *pPortDOutReg |= (1<<13);


    while(1);


}
